# Generated by Django 5.2.1 on 2025-06-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprompt',
            name='brand_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productprompt',
            name='platform',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
